language: r
cache: packages
pandoc_version: 2.9.2.1
addons:
  apt:
    packages:
    - ghostscript
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
env:
  global:
    secure: f4jL9ro3q/U1nx1JV0PxrK0c6232hylOq3plEIxbp5NQQ4ibqlk0dcRUo+SclQfJqSQMVL7XqCEEbps7/NQ31llGBpigIMf3l94lsOG6R+1pZ+FOg8Pkh4hOrlVpfqn9zGAeu9YkYWUSm06ff3nWfcgrZLkvMPCT75H6oWG8n7heoqvoIg/2rZgU7xOUmpvAdxLjnwUlnU9Cl/5nrhRvzwaBalkLQ6Y9tiCL14DsCu6RJcjBZ6StPk22ESnvfFsTrhAfDov+MaEE/5evQ+jVaiNNJWzBRlH7KklLCyG4/coIw/fGLiubAo18LbGodW2RWqZM1rX8LNikiTJkhHEPBu7dZIyjD+w6qG7q1IPXC1CxZMbFb4D888mNel9bcZE8jEjv/DP2lVn5gyO/GSlV53Zl4dW2t70i+ONDozEuvxXuSTYMsW2iQ5Ox6sqsCeBcZhvXP6nqFBxcLrocBBQYWyJqr6THoidmlnESaeaEeRnU2/OzKT/OHX5cW2CrmS5i+xOKV2PK3gVfcMiPGznJ2kWUSq0r0++JxOUYphGVMbwMj6ZEVZz08O+CBBMhsUwnQeH43p5Xdx6n35CQltNEuPaD2InV4+CvyMsu0FKKwQUBC7Eh324327dWmCOpUXyKclj/zb1XGlFloZzMsL+NhV5s6KMMKRIMz/XPdWE51q0=
